### ISSUE TITLE
jsdoc git page デプロイ

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/chirimen#116]
#107 で、生成される jsdoc を git page にデプロイする

**Comment by gurezo** [comment]
https://chirimen.github.io/chirimen/ になる想定

**Comment by gurezo** [comment]
フォーク先の実験ページ
https://gurezo.github.io/chirimen/

**Comment by gurezo** [comment]
merge されたので、 close

**Comment by kou029w** [comment]
@gurezo 
https://chirimen.org/chirimen/gc/top/examples/ 等へのリンクがいくつか存在しており、これらリンクがこわれてアクセスできなくなっていたので、GitHub Pagesを以前の設定 (/) に戻しました。

**Comment by kou029w** [comment]
JSDocによって生成されたページは代わりに http://chirimen.org/chirimen/docs/ にてホスティングされるようになっております。

**Comment by gurezo** [comment]
@kou029w 
対応ありがとうございます。
