### ISSUE TITLE
Arduino IDE Support

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/chirimen#23]
# Background
[PR14](https://github.com/chirimen-oh/chirimen-raspi3/pull/14) に伴い、Arduinoへのsketch書き込みがチュートリアルの実行に必要

# Goal
CHIRIMEN for Raspberry Pi 3は、Raspiだけで開発環境が完結できるのがウリなので、Arduino IDEも同梱できるようにしたい。

# AI
- [x] Arduino IDE インストール手順をsetup.md / setup-ja.md に追加
  - [ ] setup.sh で入れた Arduino IDE の動作確認
- [ ] Arduino IDE 同梱配布の可否を確認 (imageでの配布時) ※GPLなので問題ないはずだけど念のため
- [x] Arduino IDEと[PR14]込みのimageリリース

**Comment by tadfmac** [comment]
Ref: https://make.kosakalab.com/make/electronic-work/inst_arduino-ide_raspi/

**Comment by WhiteHawk-taka** [comment]
#39 で入りました

**Comment by tadfmac** [comment]
動いた?

**Comment by kou029w** [comment]
本件特に問題ないと思うのでクローズしますね。
