### ISSUE TITLE
競合発生時に適切なエラーメッセージを出力すべき

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen#80]
他のタブで GPIO/I2C を占有されている場合にその旨のエラーメッセージを出せるはずなのにそうしていないために非常に初学者に分かりにくい。これは Polyfill の実装・配慮不足であり修正したい。

**Comment by kou029w** [comment]
- [ ] 環境依存 (CHIRIMEN環境用) かどうかの判定
  - たとえばws connection errorだけではよく分からない

**Comment by kou029w** [comment]
いくつか比較的ポピュラーな問題に関しては日本語のエラーメッセージをDevToolsに表示するようにしました。

接続していないケース:
![2020-06-19-184149_1024x768_scrot](https://user-images.githubusercontent.com/1730234/85122141-0beee980-b261-11ea-9734-60e7bb10ecda.png)
競合しているケース:
![2020-06-19-182241_1024x768_scrot](https://user-images.githubusercontent.com/1730234/85122164-10b39d80-b261-11ea-9b22-047845b6d549.png)

PCなど未対応の環境からの接続:
![Screenshot from 2020-06-19 19-19-34](https://user-images.githubusercontent.com/1730234/85122657-df879d00-b261-11ea-9afe-3ba252881059.png)
